app_status/urls.py
from django.conf.urls import url
from .views import index, add_status

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_status.urls as app_status
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app_status/', include(app_status, namespace='app_status')),
    url(r'^$', RedirectView.as_view(url="/app_status/", permanent="true"), name='app_status'),
    #url(r'^add_message', message_post, name='add_message'),
    #url(r'^result_table', message_table, name='result_table'),
]

app_status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	message = models.CharField(max_length=100)
	created_date = models.DateTimeField(auto_now_add=True)

app_status/forms.py
from django import forms
# Create your views here.
class Message_Form(forms.Form):
    attrs = {
        'class': 'form-control'
    }

    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True, max_length=100)

app_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Status
# Create your views here.
response = {}

def index(request):
    html = 'app_status/app_status.html'
    #TODO Implement, isilah dengan 6 kata yang mendeskripsikan anda
    response['author'] = "Farhan"
    status = Status.objects.all().order_by('-created_date')
    response['status'] = status
    html = 'app_status/app_status.html'
    response['message_form'] = Message_Form
    return render(request, html, response)

def add_status(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['message'] = request.POST['message']
        status = Status(message=response['message'])
        status.save()
        html ='app_status/app_status.html'
        render(request, html, response)
        return HttpResponseRedirect('/app_status/')	
    else:        
        return HttpResponseRedirect('/add_status/')	

app_status/templates/app_status/app_status.html
{% extends "app_status/layout/base.html" %}

{% block content %}

<!--
<style>
.circular-image {
  border-radius:  50%;
  margin: 20px 0 20px 0;
  width: 100px;
  height: 100px;
}
} 
</style>
-->

<!--
<h1 class="main-title">TODOLIST</h1>
-->
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'app_status:add_status' %}" style="padding-bottom: 50px">
            <h2>Update Status</h2>
            {% csrf_token %}
            {{ message_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Post">
        </form>
    </div>
</section>

<section name = "my-status" id="my-status">
    {% for data in status %}
        <div class="flex-item" style="padding: 10px" id="statuses">
            <div style="margin-left: 100px" id = "name">
                <img src="http://www.freeiconspng.com/uploads/msn-people-person-profile-user-icon--icon-search-engine-16.png" id="circular-image"> 
                <strong>{{author}}</strong>
            </div>

            <div style="margin-left: 100px" id = "msg">
                {{data.message}}
            </div>

            <div style="margin-left: 100px" id = "time">
                {{ data.created_date }}
            </div>
        </div>
        
        <div id="space">
            {{ " " }}
        </div>
    {% endfor %}
</section>

{% endblock %}        

app_status/templates/app_status/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 5">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->

    <title>
        {% block title %} Update Status {% endblock %}
    </title>

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app_status.css' %}" />

</head>

<body>
    <header>
        {% include "app_status/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "app_status/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

app_status/templates/app_status/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -
<p>Made with Love by &copy; {{author}}</p>
-->

app_status/templates/app_status/partials/header.html
<!-- 
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
        <li><a href="{% url 'app_status:index' %}#input-list">Input Todo</a></li>
        <li><a href="{% url 'app_status:index' %}#my-list">My List</a> </li>
      </ul>
    </div>
  </div>
</nav>

-->